=== 13chetan13/Web-Technologies-Lab/w6/book.dtd
<!ELEMENT BO (B+)>
<!ELEMENT B (id,n,nop,aut,p)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT nop (#PCDATA)>
<!ELEMENT aut (#PCDATA)>
<!ELEMENT p (#PCDATA)>

=== 13chetan13/Web-Technologies-Lab/w6/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BO SYSTEM "book.dtd">

<BO>
    <B>
        <id>101</id>
        <n>JP</n>
        <nop>1000</nop>
        <aut>J</aut>
        <p>200</p>
    </B>

    <B>
        <id>101</id>
        <n>JP</n>
        <nop>1000</nop>
        <aut>J</aut>
        <p>200</p>
    </B>
</BO>
